# Generated by Django 5.2.4 on 2025-08-01 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filial', '0001_initial'),
        ('menu', '0007_alter_menucatalog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL-ключ (слаг)')),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Артикул (SKU)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Цена по умолчанию, если не переопределена в филиале.', max_digits=10, verbose_name='Базовая цена')),
                ('unit', models.CharField(blank=True, help_text='напр., шт, кг, м²', max_length=50, verbose_name='Единица измерения')),
                ('is_hidden', models.BooleanField(db_index=True, default=False, help_text='Скрыть товар со всего сайта.', verbose_name='Скрыть')),
                ('is_hit', models.BooleanField(db_index=True, default=False, help_text="Показывать в блоке 'Хиты' на главной.", verbose_name='Хит продаж')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Производитель')),
                ('country_of_origin', models.CharField(blank=True, max_length=100, verbose_name='Страна производства')),
                ('warranty_info', models.CharField(blank=True, max_length=100, verbose_name='Гарантия')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Материал')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='menu.menucatalog', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/products', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt текст (для SEO)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_main', models.BooleanField(default=False, help_text='Если отмечено, это изображение будет использоваться как главное для продукта.', verbose_name='Основное изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Изображение продукта',
                'verbose_name_plural': 'Изображения продуктов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductFilialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Оставьте пустым, чтобы использовать цену родительского филиала или базовую цену.', max_digits=10, null=True, verbose_name='Цена для филиала')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии (для филиала)')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_data', to='filial.filial', verbose_name='Филиал')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filial_data', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Данные продукта по филиалу',
                'verbose_name_plural': 'Данные продуктов по филиалам',
                'unique_together': {('product', 'filial')},
            },
        ),
    ]
