# Generated by Django 5.2.4 on 2025-08-01 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название фильтра')),
                ('slug', models.SlugField(help_text='Используется в URL (латиница, цифры, дефис)', max_length=100, unique=True, verbose_name='Ключ для URL')),
                ('order', models.PositiveIntegerField(default=100, help_text='Порядок отображения в списке фильтров', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория фильтра',
                'verbose_name_plural': 'Категории фильтров',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FilterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=255, verbose_name='Значение')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Ключ для URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.filtercategory', verbose_name='Категория фильтра')),
            ],
            options={
                'verbose_name': 'Значение фильтра',
                'verbose_name_plural': 'Значения фильтров',
                'ordering': ['category__order', 'category__name', 'order', 'value'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='filters',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.filtervalue', verbose_name='Значения фильтров'),
        ),
    ]
