# Generated by Django 5.2.4 on 2025-08-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Фиксированная цена'), ('from', 'от')], default='from', help_text="Определяет, как отображается цена (например, 'от 2000 ₽').", max_length=10, verbose_name='Тип цены'),
        ),
    ]
