# Generated by Django 5.2.4 on 2025-08-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtercategory',
            name='unit',
            field=models.CharField(blank=True, help_text="(Напр., 'мм', 'кг')", max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='product',
            name='base_name',
            field=models.CharField(blank=True, help_text="Основное название без характеристик, напр., 'Канат одинарной свивки'", max_length=200, verbose_name='Базовое название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='Генерируется автоматически при сохранении, если пустое.', max_length=100, unique=True, verbose_name='Артикул (SKU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, db_index=True, help_text='Генерируется автоматически', max_length=512, verbose_name='Полное название'),
        ),
    ]
