# Generated by Django 5.2.4 on 2025-08-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productimage_image_productimage_gallery_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='gallery_image',
        ),
    ]
