# Generated by Django 5.2.4 on 2025-08-30 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_galleryimage_options'),
        ('products', '0008_remove_productimage_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='gallery_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='gallery.galleryimage', verbose_name='Изображение из галереи'),
        ),
    ]
