# Generated by Django 5.2.4 on 2025-08-02 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filial', '0001_initial'),
        ('products', '0003_alter_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название коллекции')),
                ('slug', models.SlugField(help_text="Уникальный ключ для использования в коде и URL (напр., 'homepage-offers')", max_length=100, unique=True, verbose_name='Ключ для URL')),
                ('is_hidden', models.BooleanField(db_index=True, default=False, help_text='Скрыть коллекцию со всего сайта.', verbose_name='Скрыть')),
                ('description', models.TextField(blank=True, help_text='Внутреннее описание для администраторов.', verbose_name='Описание')),
                ('filials', models.ManyToManyField(blank=True, help_text='Выберите филиалы, в которых будет отображаться эта коллекция. Если ничего не выбрано, коллекция считается основаной.', related_name='offer_collections', to='filial.filial', verbose_name='Филиалы')),
            ],
            options={
                'verbose_name': 'Коллекция предложений',
                'verbose_name_plural': 'Коллекции предложений',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialOfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(default=100, help_text='Чем меньше число, тем выше позиция.', verbose_name='Порядок')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='offers.offercollection', verbose_name='Коллекция')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_offers', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Спецпредложение',
                'verbose_name_plural': 'Спецпредложения',
                'ordering': ['order_number'],
                'unique_together': {('collection', 'product')},
            },
        ),
    ]
