# Generated by Django 5.2.4 on 2025-08-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0001_initial'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offercollection',
            options={'ordering': ['name'], 'verbose_name': 'коллекция/продукт', 'verbose_name_plural': 'Коллекции/продукты'},
        ),
        migrations.AlterField(
            model_name='offercollection',
            name='filials',
            field=models.ManyToManyField(blank=True, help_text='Выберите филиалы, в которых будет отображаться эта коллекция', related_name='offer_collections', to='filial.filial', verbose_name='Филиалы'),
        ),
    ]
