# Generated by Django 5.2.4 on 2025-08-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_offercollection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offercollection',
            options={'ordering': ['name'], 'verbose_name': 'коллекция/Продукт', 'verbose_name_plural': 'Коллекции/Продукты'},
        ),
    ]
