# Generated by Django 5.2.4 on 2025-08-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_offercollection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='offercollection',
            name='is_default_collection',
            field=models.BooleanField(default=False, help_text='Отметьте, если эта коллекция должна использоваться по умолчанию.', verbose_name='Коллекция по умолчанию'),
        ),
    ]
