# Generated by Django 5.2.4 on 2025-08-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Фиксированная цена'), ('from', 'от')], default='fixed', max_length=10, verbose_name='Тип цены'),
        ),
    ]
