# Generated by Django 5.2.4 on 2025-08-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_orderitem_price_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zakaz',
        ),
    ]
