# Generated by Django 5.2.4 on 2025-08-23 09:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_delete_zakaz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Все заявки'},
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('cart', 'Заявка из корзины'), ('callback', 'Заказ обратного звонка'), ('consultation', 'Запрос консультации'), ('price_request', 'Запрос цены')], default='cart', max_length=20, verbose_name='Тип заявки'),
        ),
        migrations.AddField(
            model_name='order',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий / Текст заявки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='order',
            name='marketing_consent',
            field=models.BooleanField(default=False, verbose_name='Согласие на рекламу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя / Ф.И.О.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Заполняется только для заявок из корзины', max_digits=12, verbose_name='Общая стоимость'),
        ),
    ]
