# Generated by Django 5.2.4 on 2025-08-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_order_options_order_order_type_order_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('cart', 'Заявка из корзины'), ('callback', 'Заказ обратного звонка'), ('consultation', 'Запрос консультации'), ('price_request', 'Запрос цены'), ('service_request', 'Заказ услуги')], default='cart', max_length=20, verbose_name='Тип заявки'),
        ),
    ]
