# Generated by Django 5.2.4 on 2025-07-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название типа')),
                ('identifier', models.SlugField(help_text="Короткий ключ для использования в API (напр., 'catalog', 'product').", max_length=100, unique=True, verbose_name='Идентификатор для API')),
            ],
            options={
                'verbose_name': 'Тип меню',
                'verbose_name_plural': 'Типы меню',
            },
        ),
    ]
