# Generated by Django 5.2.4 on 2025-08-01 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0001_initial'),
        ('menu', '0002_typemenu_template_alter_typemenu_identifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCatalogFilialVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=True, help_text='Если отмечено, эта категория и все ее подкатегории будут скрыты в указанном филиале.', verbose_name='Скрыть в этом филиале')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filial_visibility_rules', to='menu.menucatalog', verbose_name='Категория каталога')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_categories', to='filial.filial', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Видимость категории',
                'verbose_name_plural': 'Видимость категории.',
                'unique_together': {('category', 'filial')},
            },
        ),
    ]
