# Generated by Django 5.2.4 on 2025-08-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menucatalogfilialvisibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typemenu',
            name='template',
            field=models.CharField(max_length=724, verbose_name='Название файла шаблона'),
        ),
    ]
