# Generated by Django 5.2.4 on 2025-08-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_typemenu_created_at_typemenu_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typemenu',
            options={'ordering': ['id'], 'verbose_name': 'Тип меню', 'verbose_name_plural': 'Типы меню'},
        ),
    ]
