# Generated by Django 5.2.4 on 2025-08-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_typemenu_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucatalog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/catalog/', verbose_name='Картинка'),
        ),
    ]
