# Generated by Django 5.2.4 on 2025-08-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_menucatalog_image'),
        ('products', '0002_filtercategory_filtervalue_product_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucatalog',
            name='applicable_filters',
            field=models.ManyToManyField(blank=True, help_text='Выберите, какие группы фильтров будут отображаться для товаров в этой категории.', to='products.filtercategory', verbose_name='Применимые категории фильтров'),
        ),
    ]
