# Generated by Django 5.2.4 on 2025-08-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_menucatalog_applicable_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucatalog',
            name='show_descendants_products',
            field=models.BooleanField(default=True, help_text='Если отмечено, на этой странице будут отображаться товары из всех вложенных подкатегорий. Снимите галочку, чтобы показывать только товары, напрямую связанные с этой категорией.', verbose_name='Показывать товары из подкатегорий'),
        ),
    ]
