# Generated by Django 5.2.4 on 2025-08-27 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0001_initial'),
        ('offers', '0003_alter_offercollection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='homepage_offer_collection',
            field=models.ForeignKey(blank=True, help_text='Выберите коллекцию спецпредложений, которая будет отображаться на главной странице этого филиала.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_for_filials', to='offers.offercollection', verbose_name='Коллекция спецпредложений'),
        ),
    ]
