# Generated by Django 5.2.4 on 2025-08-23 21:42

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uslugi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL-ключ (слаг)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uslugi/', verbose_name='Картинка')),
                ('description', models.CharField(max_length=512, verbose_name='Краткое описание')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Полное описание')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыть')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order_number'],
                'indexes': [models.Index(fields=['is_hidden', 'order_number'], name='idx_uslugi_hidden_order')],
            },
        ),
    ]
