# Generated by Django 5.2.4 on 2025-08-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uslugi',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова (мета)'),
        ),
        migrations.AddField(
            model_name='uslugi',
            name='keywords_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (мета)'),
        ),
        migrations.AddField(
            model_name='uslugi',
            name='title_main',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Заголовок страницы'),
        ),
    ]
