"""
Django settings for novator project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
import getpass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


SITE_NAME = 'Новатор'
VERSION_NAME = '1.0 от 31.07.25'
START_YEAR = '2025'
PROJECT_NAME = 'novator'

MAIN_DOMAIN = 'novator.test'

INFO_EMAIL = 'kouakanarnaud@gmail.com'

#SETTINGS VAR
DEFAULT_ADMIN_IMAGE_PLACEHOLDER = 'img/images/default_image.webp'
#contact session key for utm setup
CONTACTS_SESSION_KEY = 'contacts_clid'

CART_SESSION_ID = 'zakaz'

VALID_TYPE_MENU_IDS = [6, 7, 8]

RECENTLY_VIEWED_SESSION_ID = 'recently_viewed'

MAX_RECENTLY_VIEWED_ITEMS = 10

SITE_ID = 1



# Application definition

INSTALLED_APPS = [
    # --- CUSTOM APP ---
    'jazzmin',
    # 'django_celery_results',
    # 'django_celery_beat',
    'django_select2',
    # --- DJANGO APP ---
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # --- REDIRECT SITE  ---
    'django.contrib.sites',
    'django.contrib.redirects',
    # --- HUMANIZE ---
    'django.contrib.humanize',
    # --- CUSTOM LIBRARY APP ---
    'django_ckeditor_5',
    'rangefilter',
    'django_cleanup.apps.CleanupConfig',
    'solo',
    'mptt',
    'django_filters',
    # --- NOVATOR APP ---
    'apps.project_settings',
    'apps.filial',
    'apps.menu',
    'apps.products',
    'apps.offers',
    'apps.checkout',
    'apps.uslugi',
    'apps.articles',
    'apps.reviews',
    'apps.gallery',
    'apps.import_export',
    'apps.search',
    'apps.static_text',
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # --- CUSTOM MIDDLEWARE ---
    'novator.middleware.SubdomainFilialMiddleware',
    # --------- END -----------
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'novator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #Custom CONSTEXT PROCESSORS
                'apps.static_text.views.static_text',
                PROJECT_NAME + ".views.global_views",
                PROJECT_NAME + ".views.filial_context",
                PROJECT_NAME + ".views.cart_context",
            ],
        },
    },
]

WSGI_APPLICATION = 'novator.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Asia/Yekaterinburg'
# TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

USE_L10N = True


# DECIMAL_SEPARATOR = '.' 
# THOUSAND_SEPARATOR = ' '
# USE_THOUSAND_SEPARATOR = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'

WWW_ROOT ='www/'



MEDIA_ROOT = os.path.join(BASE_DIR, "www/media/")

STATIC_ROOT = os.path.join(BASE_DIR, "www/static/")


STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)


X_FRAME_OPTIONS = 'SAMEORIGIN'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


JAZZMIN_SETTINGS = {
    # "site_title": "Library Admin",
    # "site_header": "Library",
    "site_brand": "`",
    'site_logo': "img/logo/logo-novator-white.png",    
    "welcome_sign": "АДМИНИСТРИРОВАНИЕ САЙТА | НОВАТОР",

    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": "img/logo/logo-novator-h.png",

    # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark": None,

    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle_n",

    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": "img/favicon/favicon-96x96.png",

    "topmenu_links": [
        # {"name": "Категория", "url": "/novadmin/menu/menucatalog/?type_menu__id__exact=6"},
        # {"name": "Категория с продуктами", "url": "/novadmin/menu/menucatalog/?type_menu__id__exact=7"},
        # {"name": "Категория с продуктами и подкатегориями", "url": "/novadmin/menu/menucatalog/?type_menu__id__exact=8"},
        {"name": "Экспорт", "url": "/import-export/product-export/"},
        {"name": "Импорт", "url": "/import-export/product-import/"},
    ],

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    # "navigation_expanded": True,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],

    "order_with_respect_to": [
        "auth",
        "menu",
        "products",
        "gallery",
        "checkout",
        "offers",
        "filial",
        "project_settings",
        "import_export",
        "search",
        "uslugi",
        "articles",
        "reviews",
        "static_text",
        "redirects",
        "sites",
    ],
    
    "icons": {
        "menu.TypeMenu": "fas fa-bars",
        "menu.MenuCatalog": "fas fa-bars",
        "products.Product": "fas fa-th",
        "offers.OfferCollection": "fas fa-city",
        "products.FilterCategory": "fas fa-filter",
        "products.FilterValue": "fas fa-sliders-h",
        "filial.Filial": "fas fa-building",
        "admin.LogEntry": "fas fa-file",
        "project_settings.ProjectSettings": "fas fa-cogs",
        "project_settings.SocialLink": "fas fa-rss",
        "project_settings.advantage": "fas fa-check-circle",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-user-shield",
        "checkout.Order": "fas fa-shopping-cart",
        "checkout.Zakaz": "fas fa-file-alt",
        "redirects.redirect": "fas fas fa-random",
        "sites.site": "fas fa-globe",
        "uslugi.uslugi": "fas fa-concierge-bell",
        "reviews.review": "fas fa-comment-dots",
        "articles.articles": "fas fa-newspaper",
        "static_text.StaticText": "fas fa-font",
        "import_export.ImportExportLog":"fas fa-file-alt",
        "gallery.galleryimage":"fas fa-file-import",
        "search.SearchLog":"fas fa-file-alt",
    },

    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    "show_ui_builder" : False,
    
    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    # "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    # Add a language dropdown into the admin
    # "language_chooser": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-navy",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "spacelab",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}







#Custom color Palette
customColorPalette = [
        {
            'color': 'hsl(4, 90%, 58%)',
            'label': 'Red'
        },
        {
            'color': 'hsl(340, 82%, 52%)',
            'label': 'Pink'
        },
        {
            'color': 'hsl(291, 64%, 42%)',
            'label': 'Purple'
        },
        {
            'color': 'hsl(262, 52%, 47%)',
            'label': 'Deep Purple'
        },
        {
            'color': 'hsl(231, 48%, 48%)',
            'label': 'Indigo'
        },
        {
            'color': 'hsl(207, 90%, 54%)',
            'label': 'Blue'
        },
    ]

# CKEDITOR_5_CUSTOM_CSS = 'path_to.css' # optional
# CKEDITOR_5_FILE_STORAGE = "path_to_storage.CustomStorage" # optional
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                    'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],
    },
    'extends': {
        "language": "ru",
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': ['heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
        'code','subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
                    'bulletedList', 'numberedList', 'todoList', '|',  'blockQuote', 'imageUpload', '|',
                    'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
                    'insertTable',],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]

        },
        'table': {
            'contentToolbar': [ 'tableColumn', 'tableRow', 'mergeTableCells',
            'tableProperties', 'tableCellProperties' ],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'heading' : {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
                { 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' }
            ]
        },
        "htmlSupport": {
            "allow": [
                {"name": "/.*/", "attributes": True, "classes": True, "styles": True}
            ],
        },
    },
    'list': {
        'properties': {
            'styles': 'true',
            'startIndex': 'true',
            'reversed': 'true',
        }
    }
}


CKEDITOR_5_FILE_STORAGE = 'apps.utils.utils.CkeditorCustomStorage'


try:
    from .local_settings import *
except ImportError:
    from .prod_settings import *


#debug toolbar configuration 
if DEBUG:
    INSTALLED_APPS += [
        'debug_toolbar',
    ]
    MIDDLEWARE += [
        'debug_toolbar.middleware.DebugToolbarMiddleware',
    ]
    DEBUG_TOOLBAR_PANELS = [
        'debug_toolbar.panels.versions.VersionsPanel',
        'debug_toolbar.panels.timer.TimerPanel',
        'debug_toolbar.panels.settings.SettingsPanel',
        'debug_toolbar.panels.headers.HeadersPanel',
        'debug_toolbar.panels.request.RequestPanel',
        'debug_toolbar.panels.sql.SQLPanel',
        'debug_toolbar.panels.staticfiles.StaticFilesPanel',
        'debug_toolbar.panels.templates.TemplatesPanel',
        'debug_toolbar.panels.cache.CachePanel',
        'debug_toolbar.panels.signals.SignalsPanel',
        'debug_toolbar.panels.logging.LoggingPanel',
        'debug_toolbar.panels.redirects.RedirectsPanel',
        'debug_toolbar.panels.profiling.ProfilingPanel',
    ]
    INTERNAL_IPS = ('127.0.0.1',)



# #Celery result
# CELERY_RESULT_BACKEND = 'django-db'
# # # pick which cache from the CACHES setting.
# # CELERY_CACHE_BACKEND = 'default'

# CELERY_RESULT_EXTENDED = True

# CELERY_BROKER_URL = 'redis://localhost:6379/0' 
# # CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TIMEZONE = 'Asia/Yekaterinburg'


# ===================================================================
# CONFIGURATION DE CELERY
# ===================================================================
# URL du broker (Redis)
# Le format est redis://host:port/db_number
CELERY_BROKER_URL = 'redis://localhost:6379/0'

# (Optionnel) Où stocker les résultats des tâches.
# Utile pour suivre l'état des tâches, mais pas obligatoire pour les emails.
# CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# Fuseau horaire (important pour les tâches planifiées)
CELERY_TIMEZONE = 'Asia/Yekaterinburg' # Mettez votre fuseau horaire
CELERY_ENABLE_UTC = True
# ===================================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', default=25, cast=int)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)


MARKETING_ANALYST_EMAIL = 'kouakanarnaud@gmail.com'
INFO_EMAIL_RECIPIENT = 'kouakanarnaud@gmail.com'

# ===================================================================
# CONFIGURATION POUR L'ERREUR COOP EN DÉVELOPPEMENT LOCAL
# ===================================================================
# On désactive le header Cross-Origin-Opener-Policy lorsque DEBUG est True,
# car les navigateurs ne le supportent pas sur les domaines non-localhost en HTTP.
if DEBUG:
    SECURE_CROSS_ORIGIN_OPENER_POLICY = None
# ===================================================================

