# Generated by Django 5.2.4 on 2025-08-31 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchlog',
            options={'ordering': ['-search_date'], 'verbose_name': 'Поисковый запрос', 'verbose_name_plural': 'Поисковых запросов'},
        ),
    ]
