# Generated by Django 5.2.4 on 2025-08-28 17:35

import apps.import_export.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('EXPORT', 'Экспорт'), ('IMPORT', 'Импорт')], max_length=10, verbose_name='Действие')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя файла')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.import_export.models.import_export_log_path, verbose_name='Файл')),
                ('details', models.JSONField(default=dict, help_text='Контекст, такой как категория, количество строк и т.д.', verbose_name='Детали')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал импорта/экспорта',
                'verbose_name_plural': 'Журналы импорта/экспорта',
                'ordering': ['-timestamp'],
            },
        ),
    ]
