# Generated by Django 5.2.4 on 2025-08-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importexportlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Журнал имп/эксп', 'verbose_name_plural': 'Журналы имп/эксп'},
        ),
    ]
