# Generated by Django 5.2.4 on 2025-08-25 08:32

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(default=100.0, verbose_name='Порядковый номер')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=512, unique=True, verbose_name='URL-ключ')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('overview', models.CharField(max_length=512, verbose_name='Краткий обзор')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание (для SEO и превью)')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Полный текст статьи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Картинка')),
                ('title_main', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Заголовок страницы')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Ключевые слова (мета)')),
                ('keywords_description', models.TextField(blank=True, null=True, verbose_name='Описание (мета)')),
                ('is_show_main', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыть')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['order_number', '-date'],
            },
        ),
    ]
