# Generated by Django 5.2.4 on 2025-08-29 17:15

import apps.gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to=apps.gallery.models.gallery_image_upload_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, help_text='Для вашего удобства, для поиска', max_length=200, verbose_name='Название (необязательно)'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
    ]
