# Generated by Django 5.2.4 on 2025-08-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_galleryimage_image_alter_galleryimage_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Импорт изображения', 'verbose_name_plural': 'Импорт изображений'},
        ),
    ]
