# Generated by Django 5.2.4 on 2025-07-30 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название компании')),
                ('site_name', models.CharField(max_length=256, verbose_name='Название сайта')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/images', verbose_name='Логотип')),
                ('type_company', models.CharField(blank=True, max_length=256, null=True, verbose_name='Тип компании')),
                ('count_staff', models.CharField(blank=True, max_length=256, null=True, verbose_name='Количество сотрудников')),
                ('start_year', models.CharField(blank=True, max_length=50, null=True, verbose_name='Год основания')),
                ('text_head', models.TextField(blank=True, null=True, verbose_name='Блок в head (внизу)')),
                ('text_body', models.TextField(blank=True, null=True, verbose_name='Блок в body (внизу)')),
            ],
            options={
                'verbose_name': 'Настройка проекта',
                'verbose_name_plural': 'Настройки проекта',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('icon_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Название значка')),
                ('name', models.CharField(max_length=724, verbose_name='URL ссылки')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='uploads/images', verbose_name='Картинка')),
                ('is_hidden', models.BooleanField(blank=True, default=False, verbose_name='Скрыть')),
                ('project_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_settings.projectsettings')),
            ],
            options={
                'verbose_name': 'Социальная ссылка',
                'verbose_name_plural': 'Социальные ссылки',
                'ordering': ['order_number', 'name'],
            },
        ),
    ]
