# Generated by Django 5.2.4 on 2025-08-28 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('icon', models.FileField(upload_to='icons/', verbose_name='Иконка (SVG)')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Активен')),
                ('project_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='project_settings.projectsettings')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order_number'],
            },
        ),
    ]
